name: "e2e"
on: [push]
jobs:
  test-e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Install Faker library
        run: npm install @faker-js/faker --save-dev
      - name: Run your tests
        run: npx playwright test tests/HomePage.spec.ts
# Now we need to upload the test results as an artifact so that we can view them later
      - name: Upload Playwright Test Results
        if: always() 
        # This ensures that the artifact is uploaded even if the tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report from gitHub workflow
          path: test-results
          # Here only playwright test resuls are uploaded in order to get the allure report 
          # the changes are made in the playwright.config.ts file to save the allure  results in the test-results folder